from enum import StrEnum

MYSTERY_COMBAT_BASE_PROB = 0.15
MYSTERY_COMBAT_PROB_INCREASE = 0.15

MYSTERY_TREASURE_BASE_PROB = 0.02
MYSTERY_TREASURE_PROB_INCREASE = 0.02

MYSTERY_SHOPKEEP_BASE_PROB = 0.03
MYSTERY_SHOPKEEP_PROB_INCREASE = 0.03

COMBAT_ROOM_PROB = 0.54
MYSTERY_ROOM_PROB = 0.25
REST_ROOM_PROB = 0.14
SHOPKEEP_ROOM_PROB = 0.07

class Story(StrEnum):
    Underworld = "underworld"
    Ocean = "ocean"
    Forest = "forest"
    Dream = "dream"
